# Prometheus Configuration for KSET Trading Library
# Optimized for Korean financial services monitoring

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'kset-production'
    region: 'korea'
    environment: 'production'

# Rule files for alerting
rule_files:
  - "rules/*.yml"

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    metrics_path: /metrics

  # KSET Application Metrics
  - job_name: 'kset-app'
    static_configs:
      - targets: ['kset-app:9090']
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    params:
      format: ['prometheus']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'kset-app-1'

  # KSET Application Health Checks
  - job_name: 'kset-health'
    static_configs:
      - targets: ['kset-app:9090']
    scrape_interval: 30s
    metrics_path: /health
    scheme: http
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'kset-health-1'

  # PostgreSQL Database Metrics
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'kset-db-1'

  # Redis Cache Metrics
  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'kset-redis-1'

  # Node Exporter for System Metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'kset-host-1'

  # Nginx Metrics
  - job_name: 'nginx-exporter'
    static_configs:
      - targets: ['nginx-exporter:9113']
    scrape_interval: 30s
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'kset-nginx-1'

  # Docker Container Metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'kset-docker-host'

  # Process Exporter for Application Monitoring
  - job_name: 'process-exporter'
    static_configs:
      - targets: ['process-exporter:9256']
    scrape_interval: 30s
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'kset-processes'

  # Blackbox Exporter for External Monitoring
  - job_name: 'blackbox-http'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://kset.kro.kr/health
        - https://api.kset.dev/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # Blackbox Exporter for WebSocket Monitoring
  - job_name: 'blackbox-websocket'
    metrics_path: /probe
    params:
      module: [tcp_connect]
    static_configs:
      - targets:
        - kset.kro.kr:9000
        - kset.kro.kr:443
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # Korean Market Data Provider Monitoring
  - job_name: 'kiwoom-api-monitor'
    static_configs:
      - targets: ['exporter:9621']
    scrape_interval: 60s
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'kiwoom-api'

  - job_name: 'koreainvestment-api-monitor'
    static_configs:
      - targets: ['exporter:9622']
    scrape_interval: 60s
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'koreainvestment-api'

  # Business Metrics
  - job_name: 'business-metrics'
    static_configs:
      - targets: ['kset-app:9090']
    scrape_interval: 60s
    metrics_path: /metrics/business
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'kset-business'

# Remote write configuration for long-term storage
remote_write:
  - url: "https://prometheus-remote-storage.kset.dev/api/v1/write"
    basic_auth:
      username: "kset-prometheus"
      password: "${PROMETHEUS_REMOTE_PASSWORD}"
    queue_config:
      max_samples_per_send: 1000
      max_shards: 200
      capacity: 2500

# Storage configuration
storage:
  tsdb:
    retention.time: 30d
    retention.size: 10GB